import type { Player } from "../../types/player";

// Modern Arsenal squad (2020-2026)
export const MODERN_SQUAD: Omit<Player, 'meta' | 'arsenalRating'>[] = [
  {
    id: "bukayo-saka",
    slug: "bukayo-saka",
    fullName: "Bukayo Saka",
    shortName: "Bukayo Saka",
    dateOfBirth: "2001-09-05",
    nationality: "England",
    height: 178,
    preferredFoot: "Left",
    primaryPosition: "LW",
    secondaryPositions: ["LB", "RW"],
    shirtNumbers: [7],
    imageUrl: "/images/players/bukayo-saka.jpg",
    arsenalCareer: {
      startYear: 2020,
      endYear: null,
      signedFrom: "Arsenal Youth",
      soldTo: null,
      transferFeeIn: "Youth Academy",
      transferFeeOut: null,
      captain: false,
      managersPlayedUnder: ["Mikel Arteta"],
    },
    stats: {
      totalAppearances: 142,
      totalGoals: 24,
      totalAssists: 21,
      totalMinutesPlayed: 10512,
      goalsPer90: 0.21,
      assistsPer90: 0.18,
      cleanSheets: 0,
      yellowCards: 18,
      redCards: 0,
      byCompetition: [
        {
          competition: "Premier League",
          appearances: 98,
          goals: 16,
          assists: 14,
          minutesPlayed: 7290,
        },
        {
          competition: "Champions League",
          appearances: 24,
          goals: 4,
          assists: 4,
          minutesPlayed: 1728,
        },
        {
          competition: "FA Cup",
          appearances: 12,
          goals: 2,
          assists: 2,
          minutesPlayed: 864,
        },
        {
          competition: "League Cup",
          appearances: 8,
          goals: 2,
          assists: 1,
          minutesPlayed: 630,
        },
      ],
    },
    trophies: [],
  },
  {
    id: "martin-odegaard",
    slug: "martin-odegaard",
    fullName: "Martín Øde Odegaard",
    shortName: "Martin Odegaard",
    dateOfBirth: "1998-12-17",
    nationality: "Norway",
    height: 178,
    preferredFoot: "Right",
    primaryPosition: "CAM",
    secondaryPositions: ["CM", "RW"],
    shirtNumbers: [8],
    imageUrl: "/images/players/martin-odegaard.jpg",
    arsenalCareer: {
      startYear: 2021,
      endYear: null,
      signedFrom: "Real Madrid",
      soldTo: null,
      transferFeeIn: "£30m",
      transferFeeOut: null,
      captain: true,
      captainYears: "2023-Present",
      managersPlayedUnder: ["Mikel Arteta"],
    },
    stats: {
      totalAppearances: 105,
      totalGoals: 15,
      totalAssists: 18,
      totalMinutesPlayed: 8295,
      goalsPer90: 0.16,
      assistsPer90: 0.20,
      cleanSheets: 0,
      yellowCards: 12,
      redCards: 0,
      byCompetition: [
        {
          competition: "Premier League",
          appearances: 72,
          goals: 10,
          assists: 12,
          minutesPlayed: 5832,
        },
        {
          competition: "Champions League",
          appearances: 20,
          goals: 3,
          assists: 4,
          minutesPlayed: 1620,
        },
        {
          competition: "FA Cup",
          appearances: 8,
          goals: 1,
          assists: 1,
          minutesPlayed: 576,
        },
        {
          competition: "League Cup",
          appearances: 5,
          goals: 1,
          assists: 1,
          minutesPlayed: 267,
        },
      ],
    },
    trophies: [],
  },
  {
    id: "declan-rice",
    slug: "declan-rice",
    fullName: "Declan Rice",
    shortName: "Declan Rice",
    dateOfBirth: "1999-01-14",
    nationality: "England",
    height: 188,
    preferredFoot: "Right",
    primaryPosition: "CM",
    secondaryPositions: ["CDM"],
    shirtNumbers: [41],
    imageUrl: "/images/players/declan-rice.jpg",
    arsenalCareer: {
      startYear: 2023,
      endYear: null,
      signedFrom: "West Ham United",
      soldTo: null,
      transferFeeIn: "£105m",
      transferFeeOut: null,
      captain: false,
      managersPlayedUnder: ["Mikel Arteta"],
    },
    stats: {
      totalAppearances: 58,
      totalGoals: 3,
      totalAssists: 2,
      totalMinutesPlayed: 4644,
      goalsPer90: 0.06,
      assistsPer90: 0.04,
      cleanSheets: 0,
      yellowCards: 8,
      redCards: 0,
      byCompetition: [
        {
          competition: "Premier League",
          appearances: 42,
          goals: 2,
          assists: 1,
          minutesPlayed: 3360,
        },
        {
          competition: "Champions League",
          appearances: 10,
          goals: 0,
          assists: 0,
          minutesPlayed: 900,
        },
        {
          competition: "FA Cup",
          appearances: 4,
          goals: 1,
          assists: 1,
          minutesPlayed: 288,
        },
        {
          competition: "League Cup",
          appearances: 2,
          goals: 0,
          assists: 0,
          minutesPlayed: 96,
        },
      ],
    },
    trophies: [],
  },
  {
    id: "gabriel-magalhaes",
    slug: "gabriel-magalhaes",
    fullName: "Gabriel dos Santos Magalhães",
    shortName: "Gabriel",
    dateOfBirth: "1997-12-19",
    nationality: "Brazil",
    height: 188,
    preferredFoot: "Right",
    primaryPosition: "CB",
    secondaryPositions: [],
    shirtNumbers: [6],
    imageUrl: "/images/players/gabriel-magalhaes.jpg",
    arsenalCareer: {
      startYear: 2020,
      endYear: null,
      signedFrom: "Lille",
      soldTo: null,
      transferFeeIn: "£27m",
      transferFeeOut: null,
      captain: false,
      managersPlayedUnder: ["Mikel Arteta"],
    },
    stats: {
      totalAppearances: 128,
      totalGoals: 7,
      totalAssists: 1,
      totalMinutesPlayed: 11136,
      goalsPer90: 0.06,
      assistsPer90: 0.01,
      cleanSheets: 0,
      yellowCards: 16,
      redCards: 1,
      byCompetition: [
        {
          competition: "Premier League",
          appearances: 88,
          goals: 5,
          assists: 0,
          minutesPlayed: 7704,
        },
        {
          competition: "Champions League",
          appearances: 22,
          goals: 1,
          assists: 0,
          minutesPlayed: 1980,
        },
        {
          competition: "FA Cup",
          appearances: 12,
          goals: 1,
          assists: 0,
          minutesPlayed: 1080,
        },
        {
          competition: "League Cup",
          appearances: 6,
          goals: 0,
          assists: 1,
          minutesPlayed: 372,
        },
      ],
    },
    trophies: [],
  },
  {
    id: "aaron-ramsdale",
    slug: "aaron-ramsdale",
    fullName: "Aaron Ramsdale",
    shortName: "Aaron Ramsdale",
    dateOfBirth: "1998-05-14",
    nationality: "England",
    height: 188,
    preferredFoot: "Right",
    primaryPosition: "GK",
    secondaryPositions: [],
    shirtNumbers: [1],
    imageUrl: "/images/players/aaron-ramsdale.jpg",
    arsenalCareer: {
      startYear: 2021,
      endYear: null,
      signedFrom: "Sheffield United",
      soldTo: null,
      transferFeeIn: "£24m",
      transferFeeOut: null,
      captain: false,
      managersPlayedUnder: ["Mikel Arteta"],
    },
    stats: {
      totalAppearances: 86,
      totalGoals: 0,
      totalAssists: 0,
      totalMinutesPlayed: 7740,
      goalsPer90: 0,
      assistsPer90: 0,
      cleanSheets: 24,
      yellowCards: 1,
      redCards: 0,
      byCompetition: [
        {
          competition: "Premier League",
          appearances: 58,
          goals: 0,
          assists: 0,
          minutesPlayed: 5220,
          cleanSheets: 18,
        },
        {
          competition: "Champions League",
          appearances: 16,
          goals: 0,
          assists: 0,
          minutesPlayed: 1440,
          cleanSheets: 4,
        },
        {
          competition: "FA Cup",
          appearances: 8,
          goals: 0,
          assists: 0,
          minutesPlayed: 720,
          cleanSheets: 2,
        },
        {
          competition: "League Cup",
          appearances: 4,
          goals: 0,
          assists: 0,
          minutesPlayed: 360,
          cleanSheets: 0,
        },
      ],
    },
    trophies: [],
  },
  {
    id: "ben-white",
    slug: "ben-white",
    fullName: "Ben White",
    shortName: "Ben White",
    dateOfBirth: "1997-10-08",
    nationality: "England",
    height: 185,
    preferredFoot: "Right",
    primaryPosition: "CB",
    secondaryPositions: ["RB"],
    shirtNumbers: [4],
    imageUrl: "/images/players/ben-white.jpg",
    arsenalCareer: {
      startYear: 2021,
      endYear: null,
      signedFrom: "Brighton & Hove Albion",
      soldTo: null,
      transferFeeIn: "£50m",
      transferFeeOut: null,
      captain: false,
      managersPlayedUnder: ["Mikel Arteta"],
    },
    stats: {
      totalAppearances: 110,
      totalGoals: 1,
      totalAssists: 0,
      totalMinutesPlayed: 9680,
      goalsPer90: 0.01,
      assistsPer90: 0.00,
      cleanSheets: 0,
      yellowCards: 14,
      redCards: 0,
      byCompetition: [
        {
          competition: "Premier League",
          appearances: 76,
          goals: 1,
          assists: 0,
          minutesPlayed: 6840,
        },
        {
          competition: "Champions League",
          appearances: 18,
          goals: 0,
          assists: 0,
          minutesPlayed: 1620,
        },
        {
          competition: "FA Cup",
          appearances: 10,
          goals: 0,
          assists: 0,
          minutesPlayed: 900,
        },
        {
          competition: "League Cup",
          appearances: 6,
          goals: 0,
          assists: 0,
          minutesPlayed: 320,
        },
      ],
    },
    trophies: [],
  },
  {
    id: "william-saliba",
    slug: "william-saliba",
    fullName: "William Saliba",
    shortName: "William Saliba",
    dateOfBirth: "2001-03-24",
    nationality: "France",
    height: 188,
    preferredFoot: "Right",
    primaryPosition: "CB",
    secondaryPositions: [],
    shirtNumbers: [2],
    imageUrl: "/images/players/william-saliba.jpg",
    arsenalCareer: {
      startYear: 2019,
      endYear: null,
      signedFrom: "Saint-Étienne",
      soldTo: null,
      transferFeeIn: "£27m",
      transferFeeOut: null,
      captain: false,
      managersPlayedUnder: ["Mikel Arteta"],
    },
    stats: {
      totalAppearances: 94,
      totalGoals: 4,
      totalAssists: 0,
      totalMinutesPlayed: 8460,
      goalsPer90: 0.04,
      assistsPer90: 0.00,
      cleanSheets: 0,
      yellowCards: 9,
      redCards: 0,
      byCompetition: [
        {
          competition: "Premier League",
          appearances: 64,
          goals: 3,
          assists: 0,
          minutesPlayed: 5760,
        },
        {
          competition: "Champions League",
          appearances: 18,
          goals: 1,
          assists: 0,
          minutesPlayed: 1620,
        },
        {
          competition: "FA Cup",
          appearances: 8,
          goals: 0,
          assists: 0,
          minutesPlayed: 720,
        },
        {
          competition: "League Cup",
          appearances: 4,
          goals: 0,
          assists: 0,
          minutesPlayed: 360,
        },
      ],
    },
    trophies: [],
  },
];
